# Generated by Django 5.2.4 on 2025-08-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
