# Generated by Django 5.2.4 on 2025-11-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_question_donorverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='description',
            field=models.CharField(default='a des', max_length=250),
        ),
    ]
