# Generated by Django 5.2.4 on 2025-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_bloodrequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
