# Generated by Django 5.2.4 on 2025-12-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_donation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='urgency',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Urgent', 'Urgent'), ('Normal', 'Normal')], default='Normal', max_length=20),
        ),
    ]
