# Generated by Django 5.2.3 on 2026-01-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_blood_request',
        ),
        migrations.AddField(
            model_name='notification',
            name='blood_group',
            field=models.CharField(default='A+', max_length=5),
        ),
        migrations.AddField(
            model_name='notification',
            name='request_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
