# Generated by Django 5.2.3 on 2026-01-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='town',
            field=models.CharField(default='Douala', max_length=50),
        ),
    ]
